[package]
name = "treewalk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
insta = "1.41.1"
phf = { version = "0.11",features = ["macros"]  }
